version: '3'
services:
  online-notepad:
    image: online-notepad
    container_name: online-notepad
    ports:
      - "13000:3000"
    volumes:
      - ./data:/home/app/notes
    restart: always
    environment:
      - PASSWORD=${PASSWORD:-password}
