services:
  simplenote:
    build: .
    image: simplenote
    container_name: simplenote
    ports:
      - "13000:3000"
    volumes:
      - ./data:/home/app/notes
      - ./uploads:/home/app/uploads
    restart: always
    environment:
      - PASSWORD=${PASSWORD:-password}
      - JWT_SECRET=${JWT_SECRET:?JWT_SECRET is required}
